### PR TITLE
Fixed lazy loading subscribers

### PR DESCRIPTION
**Pull request by tomaskubat**
I tried to fix bellow use-case with maximum resource efficiency:

```
# config.neon
services:
    logger:
        class: Model\Logger(@rabbitmq.producer.logger)
        tags: [event.insert, event.update, event.delete]


# Model\Logger class
public function onEvents(EventsManager $em) {
    $em->on('event.insert', function($id) {
        \Tracy\Debugger::barDump('insert: ' . $id);
    });
    $em->on('event.update', function($id) {
        \Tracy\Debugger::barDump('update: ' . $id);
    });
    $em->on('event.delete', function($id) {
        \Tracy\Debugger::barDump('delete: ' . $id);
    });
}

# trigger events anywhere in app
$this->em->trigger('event.insert', '1');
$this->em->trigger('event.update', '2');
$this->em->trigger('event.delete', '3');
```

### CODE REVIEW

**Comment by f3l1x** [comment]
Thanks, but I'm not sure what this fix do. Can you explain it more?

**Comment by tomaskubat** [comment]
I would like make `Logger monitor service` (subscriber) which will listen (of course lazy) for more than one event. I realized this with code above. Just try it and look what you see in Debugger dump bar. I think it is real use-case :)

**Comment by f3l1x** [comment]
I fix it by this commit (https://github.com/minetro/events/commit/3e76c816bc9133a82900984a2c076d9be1f72240). I appreciate your fork, but you change my code. Could you please remove it?

**Comment by JanTvrdik** [comment]
@tomaskubat Why not just write your own event manager which would inherit from `Minetro\Events\EventsManager`?

**Pull request closed without merging**
